<?php include('components/header.php') ?>
<?php include('components/navbar.php') ?>
<?php include('components/main/section-1.php') ?>
<?php include('components/main/section-5.php') ?>
<?php include('components/main/section-2.php') ?>
<?php include('components/main/section-3.php') ?>
<?php include('components/main/section-4.php') ?>
<?php include('components/methodology/top-banner.php') ?>
<?php include('components/methodology/second-section.php') ?>
<?php include('components/main/section-6.php') ?>
<?php include('components/footer.php') ?>