<?php include('components/header.php') ?>
<?php include('components/navbar.php') ?>
<?php include('components/services/main-banner.php') ?>
<?php include('components/services/all-services.php') ?>
<?php include('components/marketing/marketing-banner.php') ?>
<?php include('components/marketing/marketing-carousel.php') ?>
<?php include('components/marketing/marketing-what-we-do.php') ?>
<?php include('components/marketing/marketing-services.php') ?>
<?php include('components/marketing/hero-section-marketing.php') ?>
<?php include('components/footer.php') ?>