<?php include('includes/header.php') ?>
<?php include('components/navbar/user-navbar.php') ?>
<div class="container user-form-container">
    <div class="page-marker">
        <a href="dashboard.php">
            <ion-icon name="arrow-back-outline"></ion-icon>
        </a>
        <h5>Past Payments</h5>
    </div>
    <div class="w-100">
        <form action="user-fee-search-data.php" method="POST" class="filter-row w-100">
            <input type="text" name="student_search" class="form-control filter-input-box" id="exampleFormControlInput1"
                placeholder="Enter Invoice Number, Student Name, Student Contact Number or Course to search">
            <button type="submit" name="search" class="btn btn-outline-success">Search</button>
        </form>
    </div>

    <div class="table-responsive user-table">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th scope="col">INVOICE NUMBER</th>
                    <th scope="col">INVOICE DATE</th>
                    <th scope="col">STUDENT NAME</th>
                    <th scope="col">COURSE</th>
                    <th scope="col">INVOICE VALUE</th>
                    <th scope="col">GENERATED BY</th>
                    <th scope="col">ACTION</th>
                    <th scope="col">DOWNLOAD</th>
                </tr>
            </thead>
            <tbody>
                <?php
                require('includes/connection.php');
                if (isset($_POST['search'])) {
                    $student_search = $_POST['student_search'];

                    $query = "SELECT * FROM `bora_invoice` WHERE 
                    `bora_invoice_number` LIKE '%$student_search%' OR 
                    `bora_invoice_student` LIKE '%$student_search%' OR 
                    `bora_invoice_student_contact` LIKE '%$student_search%' OR 
                    `bora_invoice_student_course` LIKE '%$student_search%'";
                    $res = mysqli_query($connection, $query);
                    if ($res) {
                        while ($row = mysqli_fetch_assoc($res)) {
                            $bora_invoice_number = $row['bora_invoice_number'];
                            $bora_invoice_date = $row['bora_invoice_date'];
                            $bora_invoice_student = $row['bora_invoice_student'];
                            $bora_invoice_student_course = $row['bora_invoice_student_course'];
                            $bora_invoice_grand_total = $row['bora_invoice_grand_total'];
                            $bora_invoice_by = $row['bora_invoice_by'];
                ?>
                <tr>
                    <th scope="row"><?php echo $bora_invoice_number ?></th>
                    <td><?php echo $bora_invoice_date ?></td>
                    <td><?php echo $bora_invoice_student ?></td>
                    <td><?php echo $bora_invoice_student_course ?></td>
                    <td><?php echo $bora_invoice_grand_total ?></td>
                    <td><?php echo $bora_invoice_by ?></td>
                    <td>
                        <form action="user-student-details.php" method="post">
                            <input type="text" value="<?php echo $student_id ?>" name="student_id" hidden>
                            <button type="submit" name="edit" class="btn btn-sm btn-outline-success">View
                                Details</button>
                        </form>
                    </td>
                    <td>
                        <form action="user-collect-fee.php" method="POST">
                            <input type="text" value="<?php echo $student_id ?>" name="student_id" hidden>
                            <button type="submit" name="collect" class="btn btn-sm btn-outline-warning">Collect
                                Fee</button>
                        </form>
                    </td>
                </tr>
                <?php
                        }
                    } else {
                        echo "Data Not Found";
                    }
                }
                ?>
            </tbody>
        </table>
    </div>
</div>
<?php include('includes/footer.php') ?>